//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exercise4_Garage_2.MenuClasses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exercise4_Garage_2.MenuClasses.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to antal fordon i garaget.
        /// </summary>
        public static string AntalFordon {
            get {
                return ResourceManager.GetString("AntalFordon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  av .
        /// </summary>
        public static string Av {
            get {
                return ResourceManager.GetString("Av", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to avsluta.
        /// </summary>
        public static string Avsluta {
            get {
                return ResourceManager.GetString("Avsluta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tillbaka.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bil.
        /// </summary>
        public static string Bil {
            get {
                return ResourceManager.GetString("Bil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to båt.
        /// </summary>
        public static string Boat {
            get {
                return ResourceManager.GetString("Boat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to max hastighet (knop).
        /// </summary>
        public static string BoatSpeed {
            get {
                return ResourceManager.GetString("BoatSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buss.
        /// </summary>
        public static string Buss {
            get {
                return ResourceManager.GetString("Buss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to färg.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (1. Röd, 2. Blå, 3. Grön, 4. Gul 5. Svart).
        /// </summary>
        public static string ColorChoise {
            get {
                return ResourceManager.GetString("ColorChoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor storlek i CC.
        /// </summary>
        public static string CubicInch {
            get {
                return ResourceManager.GetString("CubicInch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aktivt bibliotek.
        /// </summary>
        public static string CurrentDir {
            get {
                return ResourceManager.GetString("CurrentDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denna bilen .
        /// </summary>
        public static string DennaBilen {
            get {
                return ResourceManager.GetString("DennaBilen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denna bussen .
        /// </summary>
        public static string DennaBussen {
            get {
                return ResourceManager.GetString("DennaBussen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denna motorcykeln .
        /// </summary>
        public static string DennaMotorcykeln {
            get {
                return ResourceManager.GetString("DennaMotorcykeln", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deplacement.
        /// </summary>
        public static string Deplac {
            get {
                return ResourceManager.GetString("Deplac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ange deplacement.
        /// </summary>
        public static string Deplacement {
            get {
                return ResourceManager.GetString("Deplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to avsluta.
        /// </summary>
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to felaktig input.
        /// </summary>
        public static string FelaktigInput {
            get {
                return ResourceManager.GetString("FelaktigInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filer i .
        /// </summary>
        public static string FilesIn {
            get {
                return ResourceManager.GetString("FilesIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flygplan.
        /// </summary>
        public static string Flygplan {
            get {
                return ResourceManager.GetString("Flygplan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  fordon kan få plats..
        /// </summary>
        public static string FordonKanFaPlats {
            get {
                return ResourceManager.GetString("FordonKanFaPlats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fordon med Registrering.
        /// </summary>
        public static string FordonMedRegistrering {
            get {
                return ResourceManager.GetString("FordonMedRegistrering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garaget.
        /// </summary>
        public static string Garage {
            get {
                return ResourceManager.GetString("Garage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garage 2.0.
        /// </summary>
        public static string GarageVer {
            get {
                return ResourceManager.GetString("GarageVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to har tagits bort.
        /// </summary>
        public static string HarTagitsBort {
            get {
                return ResourceManager.GetString("HarTagitsBort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hittades.
        /// </summary>
        public static string Hittades {
            get {
                return ResourceManager.GetString("Hittades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hittades ej..
        /// </summary>
        public static string HittadesEj {
            get {
                return ResourceManager.GetString("HittadesEj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hur många .
        /// </summary>
        public static string HurManga {
            get {
                return ResourceManager.GetString("HurManga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to är fullt..
        /// </summary>
        public static string IsFull {
            get {
                return ResourceManager.GetString("IsFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lägg till .
        /// </summary>
        public static string LaggTill {
            get {
                return ResourceManager.GetString("LaggTill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to har lagts till i garaget..
        /// </summary>
        public static string LagtsTillGaraget {
            get {
                return ResourceManager.GetString("LagtsTillGaraget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to längd.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lyftkapacitet .
        /// </summary>
        public static string Lyftkapacitet {
            get {
                return ResourceManager.GetString("Lyftkapacitet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huvudmeny.
        /// </summary>
        public static string MainHeader {
            get {
                return ResourceManager.GetString("MainHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ange max hastighet (knop).
        /// </summary>
        public static string MaxSpeed {
            get {
                return ResourceManager.GetString("MaxSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ange djupgående (m).
        /// </summary>
        public static string MaxWaterDepth {
            get {
                return ResourceManager.GetString("MaxWaterDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to med registreringsnummer.
        /// </summary>
        public static string medRegistrering {
            get {
                return ResourceManager.GetString("medRegistrering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to motorcykel.
        /// </summary>
        public static string Motorcykel {
            get {
                return ResourceManager.GetString("Motorcykel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to antal dörrar.
        /// </summary>
        public static string NumDoors {
            get {
                return ResourceManager.GetString("NumDoors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to antal säten.
        /// </summary>
        public static string NumSeats {
            get {
                return ResourceManager.GetString("NumSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to passagerare.
        /// </summary>
        public static string Pax {
            get {
                return ResourceManager.GetString("Pax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  platser..
        /// </summary>
        public static string platser {
            get {
                return ResourceManager.GetString("platser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bil.
        /// </summary>
        public static string Rad1AddVehicle {
            get {
                return ResourceManager.GetString("Rad1AddVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svenska.
        /// </summary>
        public static string Rad1ChooseLanguage {
            get {
                return ResourceManager.GetString("Rad1ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ladda sparade fordon från fil..
        /// </summary>
        public static string Rad1LoadVehicleFromFilePart1 {
            get {
                return ResourceManager.GetString("Rad1LoadVehicleFromFilePart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spara fordon till fil..
        /// </summary>
        public static string Rad1LoadVehicleFromFilePart2 {
            get {
                return ResourceManager.GetString("Rad1LoadVehicleFromFilePart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lägg till fordon.
        /// </summary>
        public static string Rad1Main {
            get {
                return ResourceManager.GetString("Rad1Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sök och ta bort fordon.
        /// </summary>
        public static string Rad1RemoveVehicle {
            get {
                return ResourceManager.GetString("Rad1RemoveVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa alla fordon.
        /// </summary>
        public static string Rad1ShowVehicle {
            get {
                return ResourceManager.GetString("Rad1ShowVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buss.
        /// </summary>
        public static string Rad2AddVehicle {
            get {
                return ResourceManager.GetString("Rad2AddVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engelska.
        /// </summary>
        public static string Rad2ChooseLanguage {
            get {
                return ResourceManager.GetString("Rad2ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort fordon.
        /// </summary>
        public static string Rad2Main {
            get {
                return ResourceManager.GetString("Rad2Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort fordon på regnummer.
        /// </summary>
        public static string Rad2RemoveVehicle {
            get {
                return ResourceManager.GetString("Rad2RemoveVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa fordon via regnummer.
        /// </summary>
        public static string Rad2ShowVehicle {
            get {
                return ResourceManager.GetString("Rad2ShowVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motorcykel.
        /// </summary>
        public static string Rad3AddVehicle {
            get {
                return ResourceManager.GetString("Rad3AddVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa fordon.
        /// </summary>
        public static string Rad3Main {
            get {
                return ResourceManager.GetString("Rad3Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sök fordon på typ, regnummer, färg, vikt, längd.
        /// </summary>
        public static string Rad3ShowVehicle {
            get {
                return ResourceManager.GetString("Rad3ShowVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Båt.
        /// </summary>
        public static string Rad4AddVehicle {
            get {
                return ResourceManager.GetString("Rad4AddVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hämta/Spara fordon.
        /// </summary>
        public static string Rad4Main {
            get {
                return ResourceManager.GetString("Rad4Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flygplan.
        /// </summary>
        public static string Rad5AddVehicle {
            get {
                return ResourceManager.GetString("Rad5AddVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Välj språk.
        /// </summary>
        public static string Rad5Main {
            get {
                return ResourceManager.GetString("Rad5Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slumpmässigt.
        /// </summary>
        public static string Rad6AddVehicle {
            get {
                return ResourceManager.GetString("Rad6AddVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lägg till fordonsdetaljer.
        /// </summary>
        public static string RadAddVehicle {
            get {
                return ResourceManager.GetString("RadAddVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registreringsnummer.
        /// </summary>
        public static string RegNum {
            get {
                return ResourceManager.GetString("RegNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garage 2.0.
        /// </summary>
        public static string Rubrik {
            get {
                return ResourceManager.GetString("Rubrik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  slumpade fordon..
        /// </summary>
        public static string SlumpadeFordon {
            get {
                return ResourceManager.GetString("SlumpadeFordon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  slumpade fordon har lagts till garaget..
        /// </summary>
        public static string SlumpadeFordonHarLagtsTillIGaraget {
            get {
                return ResourceManager.GetString("SlumpadeFordonHarLagtsTillIGaraget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sök och filtrera fordon.
        /// </summary>
        public static string SokOchFiltrera {
            get {
                return ResourceManager.GetString("SokOchFiltrera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spara i denna katalog (Yes/No/Abort - Enter).
        /// </summary>
        public static string SparaIKatalog {
            get {
                return ResourceManager.GetString("SparaIKatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort fordon.
        /// </summary>
        public static string TaBortFordon {
            get {
                return ResourceManager.GetString("TaBortFordon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  togs bort från garaget. .
        /// </summary>
        public static string TogsBortGaraget {
            get {
                return ResourceManager.GetString("TogsBortGaraget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tryck Retur för att fortsätta....
        /// </summary>
        public static string TryckRetur {
            get {
                return ResourceManager.GetString("TryckRetur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Välj.
        /// </summary>
        public static string Valg {
            get {
                return ResourceManager.GetString("Valg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Välj någon av dessa filer (Yes/No/Abort - Enter).
        /// </summary>
        public static string ValgDassaFiler {
            get {
                return ResourceManager.GetString("ValgDassaFiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Välj bibliotek.
        /// </summary>
        public static string ValjBibliotek {
            get {
                return ResourceManager.GetString("ValjBibliotek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Välj fil.
        /// </summary>
        public static string ValjFil {
            get {
                return ResourceManager.GetString("ValjFil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fordon inlästa från fil.
        /// </summary>
        public static string VehicleLodedFrom {
            get {
                return ResourceManager.GetString("VehicleLodedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vikt.
        /// </summary>
        public static string Vikt {
            get {
                return ResourceManager.GetString("Vikt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vill du söka efter en 1. Bil, 2. Buss, 3. Motorcykel, 4. Båt, 5. Flygplan.
        /// </summary>
        public static string VillDuSokaEfter {
            get {
                return ResourceManager.GetString("VillDuSokaEfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spännvidd.
        /// </summary>
        public static string Vingbredd {
            get {
                return ResourceManager.GetString("Vingbredd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to djupgående.
        /// </summary>
        public static string WaterDepth {
            get {
                return ResourceManager.GetString("WaterDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hjul.
        /// </summary>
        public static string Wheel {
            get {
                return ResourceManager.GetString("Wheel", resourceCulture);
            }
        }
    }
}
