//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exercise4_Garage_2.MenuClasses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exercise4_Garage_2.MenuClasses.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bil.
        /// </summary>
        internal static string Bil {
            get {
                return ResourceManager.GetString("Bil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to färg.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to längd.
        /// </summary>
        internal static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to med registreringsnummer:.
        /// </summary>
        internal static string medRegistrering {
            get {
                return ResourceManager.GetString("medRegistrering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to antal dörrar.
        /// </summary>
        internal static string NumDoors {
            get {
                return ResourceManager.GetString("NumDoors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garage 2.0.
        /// </summary>
        internal static string Rubrik {
            get {
                return ResourceManager.GetString("Rubrik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vikt.
        /// </summary>
        internal static string Vikt {
            get {
                return ResourceManager.GetString("Vikt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hjul.
        /// </summary>
        internal static string Wheel {
            get {
                return ResourceManager.GetString("Wheel", resourceCulture);
            }
        }
    }
}
