//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exercise4_Garage_2.MenuClasses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exercise4_Garage_2.MenuClasses.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to antal fordon i garaget.
        /// </summary>
        internal static string AntalFordon {
            get {
                return ResourceManager.GetString("AntalFordon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  av .
        /// </summary>
        internal static string Av {
            get {
                return ResourceManager.GetString("Av", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to avsluta.
        /// </summary>
        internal static string Avsluta {
            get {
                return ResourceManager.GetString("Avsluta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tillbaka.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bil.
        /// </summary>
        internal static string Bil {
            get {
                return ResourceManager.GetString("Bil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to båt.
        /// </summary>
        internal static string Boat {
            get {
                return ResourceManager.GetString("Boat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buss.
        /// </summary>
        internal static string Buss {
            get {
                return ResourceManager.GetString("Buss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to färg.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (1. Röd, 2. Blå, 3. Grön, 4. Gul 5. Svart).
        /// </summary>
        internal static string ColorChoise {
            get {
                return ResourceManager.GetString("ColorChoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor storlek i CC.
        /// </summary>
        internal static string CubicInch {
            get {
                return ResourceManager.GetString("CubicInch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denna bilen .
        /// </summary>
        internal static string DennaBilen {
            get {
                return ResourceManager.GetString("DennaBilen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denna bussen .
        /// </summary>
        internal static string DennaBussen {
            get {
                return ResourceManager.GetString("DennaBussen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denna motorcykeln .
        /// </summary>
        internal static string DennaMotorcykeln {
            get {
                return ResourceManager.GetString("DennaMotorcykeln", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ange deplacement.
        /// </summary>
        internal static string Deplacement {
            get {
                return ResourceManager.GetString("Deplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to avsluta.
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flygplan.
        /// </summary>
        internal static string Flygplan {
            get {
                return ResourceManager.GetString("Flygplan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lägg till .
        /// </summary>
        internal static string LaggTill {
            get {
                return ResourceManager.GetString("LaggTill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to har lagts till i garaget..
        /// </summary>
        internal static string LagtsTillGaraget {
            get {
                return ResourceManager.GetString("LagtsTillGaraget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to längd.
        /// </summary>
        internal static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huvudmeny.
        /// </summary>
        internal static string MainHeader {
            get {
                return ResourceManager.GetString("MainHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ange max hastighet (knop).
        /// </summary>
        internal static string MaxSpeed {
            get {
                return ResourceManager.GetString("MaxSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ange djupgående (m).
        /// </summary>
        internal static string MaxWaterDepth {
            get {
                return ResourceManager.GetString("MaxWaterDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to med registreringsnummer:.
        /// </summary>
        internal static string medRegistrering {
            get {
                return ResourceManager.GetString("medRegistrering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to motorcykel.
        /// </summary>
        internal static string Motorcykel {
            get {
                return ResourceManager.GetString("Motorcykel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to antal dörrar.
        /// </summary>
        internal static string NumDoors {
            get {
                return ResourceManager.GetString("NumDoors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to antal säten.
        /// </summary>
        internal static string NumSeats {
            get {
                return ResourceManager.GetString("NumSeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  platser..
        /// </summary>
        internal static string platser {
            get {
                return ResourceManager.GetString("platser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bil.
        /// </summary>
        internal static string Rad1AddVehicle {
            get {
                return ResourceManager.GetString("Rad1AddVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Svenska.
        /// </summary>
        internal static string Rad1ChooseLanguage {
            get {
                return ResourceManager.GetString("Rad1ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ladda sparade fordon i befintlig garage storlek..
        /// </summary>
        internal static string Rad1LoadVehicleFromFilePart1 {
            get {
                return ResourceManager.GetString("Rad1LoadVehicleFromFilePart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det aktuella garaget sparas automatiskt vid avslut..
        /// </summary>
        internal static string Rad1LoadVehicleFromFilePart2 {
            get {
                return ResourceManager.GetString("Rad1LoadVehicleFromFilePart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lägg till fordon.
        /// </summary>
        internal static string Rad1Main {
            get {
                return ResourceManager.GetString("Rad1Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sök och ta bort fordon.
        /// </summary>
        internal static string Rad1RemoveVehicle {
            get {
                return ResourceManager.GetString("Rad1RemoveVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa alla fordon.
        /// </summary>
        internal static string Rad1ShowVehicle {
            get {
                return ResourceManager.GetString("Rad1ShowVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buss.
        /// </summary>
        internal static string Rad2AddVehicle {
            get {
                return ResourceManager.GetString("Rad2AddVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engelska.
        /// </summary>
        internal static string Rad2ChooseLanguage {
            get {
                return ResourceManager.GetString("Rad2ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort fordon.
        /// </summary>
        internal static string Rad2Main {
            get {
                return ResourceManager.GetString("Rad2Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort fordon på regnummer.
        /// </summary>
        internal static string Rad2RemoveVehicle {
            get {
                return ResourceManager.GetString("Rad2RemoveVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa fordon via regnummer.
        /// </summary>
        internal static string Rad2ShowVehicle {
            get {
                return ResourceManager.GetString("Rad2ShowVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motorcykel.
        /// </summary>
        internal static string Rad3AddVehicle {
            get {
                return ResourceManager.GetString("Rad3AddVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa fordon.
        /// </summary>
        internal static string Rad3Main {
            get {
                return ResourceManager.GetString("Rad3Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sök fordon på typ, regnummer, färg, vikt, längd.
        /// </summary>
        internal static string Rad3ShowVehicle {
            get {
                return ResourceManager.GetString("Rad3ShowVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Båt.
        /// </summary>
        internal static string Rad4AddVehicle {
            get {
                return ResourceManager.GetString("Rad4AddVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hämta fordon från fil.
        /// </summary>
        internal static string Rad4Main {
            get {
                return ResourceManager.GetString("Rad4Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flygplan.
        /// </summary>
        internal static string Rad5AddVehicle {
            get {
                return ResourceManager.GetString("Rad5AddVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Välj språk.
        /// </summary>
        internal static string Rad5Main {
            get {
                return ResourceManager.GetString("Rad5Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slumpmässigt.
        /// </summary>
        internal static string Rad6AddVehicle {
            get {
                return ResourceManager.GetString("Rad6AddVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lägg till fordonsdetaljer.
        /// </summary>
        internal static string RadAddVehicle {
            get {
                return ResourceManager.GetString("RadAddVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registreringsnummer.
        /// </summary>
        internal static string RegNum {
            get {
                return ResourceManager.GetString("RegNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garage 2.0.
        /// </summary>
        internal static string Rubrik {
            get {
                return ResourceManager.GetString("Rubrik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tryck Retur för att fortsätta....
        /// </summary>
        internal static string TryckRetur {
            get {
                return ResourceManager.GetString("TryckRetur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Välj.
        /// </summary>
        internal static string Valg {
            get {
                return ResourceManager.GetString("Valg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vikt.
        /// </summary>
        internal static string Vikt {
            get {
                return ResourceManager.GetString("Vikt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hjul.
        /// </summary>
        internal static string Wheel {
            get {
                return ResourceManager.GetString("Wheel", resourceCulture);
            }
        }
    }
}
