# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: xUnit Test Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
  
      - name: Restore
        run: dotnet restore Exercise4_Garage_2b/Exercise4_Garage_2b/Exercise4_Garage_2b.csproj

      - name: Build Main proj
        run: dotnet build Exercise4_Garage_2b/Exercise4_Garage_2b/Exercise4_Garage_2b.csproj --no-restore --configuration Release

      - name: Restore
        run: dotnet restore Exercise4_Garage_2b/Exercise4_Garage_2b.Tests/Exercise4_Garage_2b.Tests.csproj
  
      - name: Build Test project
        run: dotnet build Exercise4_Garage_2b/Exercise4_Garage_2b.Tests/Exercise4_Garage_2b.Tests.csproj --no-restore
        
      - name: Run tests
        env:
          DOTNET_TEST_NEW_VSTEST_EXPERIENCE: "true" # Detta aktiverar stöd för .NET 10+
        run: dotnet test Exercise4_Garage_2b/Exercise4_Garage_2b.Tests/Exercise4_Garage_2b.Tests.csproj --no-build
