# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Bulid

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Build main project
      run: dotnet build Exercise4_Garage_2b/Exercise4_Garage_2/Exercise4_Garage_2b.csproj --no-restore --configuration Release

    - name: Build test project
      run: dotnet build Exercise4_Garage_2b/Exercise4_Garage_2b.Tests/Exercise4_Garage_2b.Tests.csproj --no-restore --configuration Release
      
    - name: Test
      run: dotnet test Exercise4_Garage_2b/Exercise4_Garage_2b.Tests/Exercise4_Garage_2b.Tests.csproj --no-build --configuration Release
